# machine: adjust the behavior of the virtual machine (VM)
# checkout: checkout and clone code from a repository
# dependencies: install your project’s language-specific dependencies
# database: prepare a database for tests
# compile: compile your project
# test: run your tests
# deployment: deploy your code to your web servers
version: 2
jobs:
  build:
    working_directory: ~/koa2-api-boilerplate
    # The primary container is an instance of the first list image listed. Your build commands run in this container.
    docker:
      - image: circleci/node:7.10
    # The secondary container is an instance of the second listed image which is run in a common network where ports exposed on the primary container are available on localhost.
      - image: mongo:3.4.4
    steps:
      - checkout
      - run:
          name: update-npm
          command: 'sudo npm install -g npm@latest'
      - restore_cache:
          key: dependency-cache-{{ checksum "package.json" }}
      - run:
          name: install-npm-wee
          command: npm install
      - save_cache:
          key: dependency-cache-{{ checksum "package.json" }}
          paths:
            - .node_modules
  test:
    docker:
      - image: circleci/node:7.10
      - image: mongo:3.4.4
    steps:
      - checkout
      - run:
          name: test
          command: npm test
      - run:
          name: code-coverage
          command: './node_modules/bin/nyc report --reporter=text-lcov'
      - store_artifacts:
          path: test-results.xml
          prefix: tests
      - store_artifacts:
          path: coverage
          prefix: coverage

workflows:
  version: 2
  build_and_test:
    jobs:
      - build
      - test:
          requires:
            - build
          filters:
            branches:
              only: master
