# machine: adjust the behavior of the virtual machine (VM)
# checkout: checkout and clone code from a repository
# dependencies: install your project’s language-specific dependencies
# database: prepare a database for tests
# compile: compile your project
# test: run your tests
# deployment: deploy your code to your web servers
version: 2
jobs:
  build:
    docker:
      - image: circleci/node:7.10
    steps:
      - checkout
      - run: echo "hello world"
